name: PR Gradle Build CI

on:
  pull_request:
    branches:
      - main
      - develop

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up JDK 23
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '23'
          cache: 'gradle'

      - name: Grant Execute Permission to Gradle
        run: chmod +x ./gradlew

      - name: Run Gradle Clean Build
        run: ./gradlew clean build

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-output
          path: build/libs  # 빌드 결과물 업로드 (옵션)